[package]
name = "aptos_nft_bridge"
version = "1.0.0"
authors = []

[addresses]
bridge="_" # set this to the admin account when deploying to mainnetS
test="_"

[dev-addresses]
bridge="fcd5f124f883318db139691550c18fbbc927d07567e1f913a30b512b06bb836c"
test="eb9e6d083dd721fab761a07d17d563f1337c8900a3a2e99b76ed0f9fdea8fc97"

[dependencies]
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
# AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "devnet" }
# AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "devnet" }
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework", rev = "devnet" }
AptosTokenObjects = { local = "../../aptos-core/aptos-move/framework/aptos-token-objects/", rev = "devnet" }
AptosStdlib = { local = "../../aptos-core/aptos-move/framework/aptos-stdlib" }

[dev-dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework", rev = "devnet" }
AptosTokenObjects = { local = "../../aptos-core/aptos-move/framework/aptos-token-objects/", rev = "devnet" }
AptosStdlib = { local = "../../aptos-core/aptos-move/framework/aptos-stdlib" }
