[package]
name = "aptos_nft_bridge"
version = "1.0.0"
authors = []

[addresses]
bridge="13f8d626e383e8621a89caeb05c56a95fda38aa2dddfa8c2b1ed063f0edb23c9" # set this to the admin account when deploying to mainnet
nftowner="b6e6997831b43973c56cfa75f283288a37587c4e76d422d2f88b399b0a9cf206"

# [dev-addresses]
# bridge="e2006dfacb95fced3793a1c9c75511abbf41c893fb9ea544bb6c43b8be53bbef"
# nftowner="763954411e5a1f5f9d7a1b595ad6ff5a6e7cdf8650e8e00ece01707fcd6c778a"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "devnet" }
AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "devnet" }

[dev-dependencies]
