[package]
name = "aptos_nft_bridge"
version = "1.0.0"
authors = []

[addresses]
bridge="_" # set this to the admin account when deploying to mainnet
nftowner="_"

[dev-addresses]
bridge="fe114e06fcf0e85325992fdd9d03b056949a9aa6f899265266859729d2d3471b"
nftowner="2681bdebd4316be3e6c6bd7547afedc1b9956be58211b022fcebc4928bf0757c"

[dependencies]
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "devnet" }
# AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects/", rev = "devnet" }
# AptosStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-stdlib", rev = "devnet" }
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework", rev = "devnet" }
AptosTokenObjects = { local = "../../aptos-core/aptos-move/framework/aptos-token-objects/", rev = "devnet" }
AptosStdlib = { local = "../../aptos-core/aptos-move/framework/aptos-stdlib" }

[dev-dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework", rev = "devnet" }
AptosTokenObjects = { local = "../../aptos-core/aptos-move/framework/aptos-token-objects/", rev = "devnet" }
AptosStdlib = { local = "../../aptos-core/aptos-move/framework/aptos-stdlib" }
