const BRIDGE_ADDRESS =
  "4894ba94151905fb7e74c7e65c7c2a078b1e291aa19d340533159268ee552f94";

const BRIDGE_MODULE = "aptos_nft_bridge";

const BRIDGE_FUNCTIONS = {
  Initialize: "initialize",
};

enum CONTRACT_ERROR_CODES {
  E_ALREADY_INITIALIZED = "E_ALREADY_INITIALIZED",
  E_NOT_BRIDGE_ADMIN = "E_NOT_BRIDGE_ADMIN",
  E_VALIDATORS_LENGTH_ZERO = "E_VALIDATORS_LENGTH_ZERO",
  E_VALIDATOR_ALREADY_EXIST = "E_VALIDATOR_ALREADY_EXIST",
  THERSHOLD_NOT_REACHED = "THERSHOLD_NOT_REACHED",
  E_INVALID_GK = "E_INVALID_GK",
  E_INVALID_SIGNATURE = "E_INVALID_SIGNATURE",
  E_NOT_INITIALIZED = "E_NOT_INITIALIZED",
  E_INVALID_FEE = "E_INVALID_FEE",
  E_NO_REWARDS_AVAILABLE = "E_NO_REWARDS_AVAILABLE",
  E_INVALID_DESTINATION_CHAIN = "E_INVALID_DESTINATION_CHAIN",
  E_INVALID_NFT_TYPE = "E_INVALID_NFT_TYPE",
}

export {
  BRIDGE_ADDRESS,
  BRIDGE_MODULE,
  BRIDGE_FUNCTIONS,
  CONTRACT_ERROR_CODES,
};
