const BRIDGE_ADDRESS =
  "913d9c69bba191be0d283390df53b75b94158cd11697436274191f0a363ccc13";

const BRIDGE_MODULE = "aptos_nft_bridge";
const MINT_MODULE = "mint";

const BRIDGE_FUNCTIONS = {
  Initialize: "initialize",
  MoveBridgeResource: "move_bridge_resource",
  AddValidator: "add_validator",
  Lock721: "lock_721",
  Lock1155: "lock_1155",
  Claim721: "claim_721",
  Claim1155: "claim_1155",
  OwnsNFT: "owns_nft",
};

const MINT_FUNCTIONS = {
  MINT_TO: "mint_to",
  MINT_1155_TO: "mint_1155_to",
};

enum CONTRACT_ERROR_CODES {
  E_ALREADY_INITIALIZED = "E_ALREADY_INITIALIZED",
  E_NOT_BRIDGE_ADMIN = "E_NOT_BRIDGE_ADMIN",
  E_VALIDATORS_LENGTH_ZERO = "E_VALIDATORS_LENGTH_ZERO",
  E_VALIDATOR_ALREADY_EXIST = "E_VALIDATOR_ALREADY_EXIST",
  E_THERSHOLD_NOT_REACHED = "E_THERSHOLD_NOT_REACHED",
  E_INVALID_GK = "E_INVALID_GK",
  E_INVALID_SIGNATURE = "E_INVALID_SIGNATURE",
  E_NOT_INITIALIZED = "E_NOT_INITIALIZED",
  E_INVALID_FEE = "E_INVALID_FEE",
  E_NO_REWARDS_AVAILABLE = "E_NO_REWARDS_AVAILABLE",
  E_INVALID_DESTINATION_CHAIN = "E_INVALID_DESTINATION_CHAIN",
  E_INVALID_NFT_TYPE = "E_INVALID_NFT_TYPE",
  E_SIGNATURES_PUBLIC_KEYS_LENGTH_NOT_SAME = "E_SIGNATURES_PUBLIC_KEYS_LENGTH_NOT_SAME",
  EOBJECT_DOES_NOT_EXIST = "EOBJECT_DOES_NOT_EXIST",
  E_TOKEN_AMOUNT_IS_ZERO = "E_TOKEN_AMOUNT_IS_ZERO",
  E_CLAIM_ALREADY_PROCESSED = "E_CLAIM_ALREADY_PROCESSED",
  EINSUFFICIENT_BALANCE = "EINSUFFICIENT_BALANCE",
}

const CHAIN_ID = "APTOS";

export {
  BRIDGE_ADDRESS,
  BRIDGE_MODULE,
  BRIDGE_FUNCTIONS,
  CONTRACT_ERROR_CODES,
  CHAIN_ID,
  MINT_MODULE,
  MINT_FUNCTIONS,
};
